"""M21: divisibility down-set generated by the M20 profile (4,2,1,1,1,1)."""
from __future__ import annotations
from m17_infinite_family import is_prime
from m20_exponent_profile import proof_branch as m20_proof_branch

EXCLUDED_SORTED_PROFILES=(
    (1,1,1,1,1,1),
    (2,1,1,1,1,1),
    (2,2,1,1,1,1),
    (3,1,1,1,1,1),
    (3,2,1,1,1,1),
    (4,1,1,1,1,1),
    (4,2,1,1,1,1),
)

def family_number(primes:tuple[int,...],exponents:tuple[int,...])->int:
    out=1
    for p,a in zip(primes,exponents): out*=p**a
    return out

def dominant_m20_exponents(primes:tuple[int,...],exponents:tuple[int,...])->tuple[int,...]:
    if len(primes)!=6 or len(exponents)!=6: raise ValueError("need six coordinates")
    if len(set(primes))!=6 or not all(is_prime(p) and p%2==1 for p in primes): raise ValueError("need six distinct odd primes")
    if any(a<1 for a in exponents): raise ValueError("exponents must be positive")
    ranked=sorted(range(6),key=lambda i:(-exponents[i],i))
    sorted_exp=tuple(sorted(exponents,reverse=True))
    if not (sorted_exp[0]<=4 and sorted_exp[1]<=2 and sorted_exp[2:]==(1,1,1,1)):
        raise ValueError("profile is outside the M21 down-set")
    major=[1]*6
    major[ranked[0]]=4
    major[ranked[1]]=2
    major=tuple(major)
    assert all(a<=b for a,b in zip(exponents,major))
    return major

def downset_proof_branch(primes:tuple[int,...],exponents:tuple[int,...])->dict:
    major=dominant_m20_exponents(primes,exponents)
    n=family_number(primes,exponents)
    n_tilde=family_number(primes,major)
    assert n_tilde%n==0
    branch=m20_proof_branch(primes,major)
    return {"N":n,"N_tilde":n_tilde,"dominant_exponents":major,"m20_branch":branch,"divides":True,"noncovering_by_divisibility":True}

def profile_downset_audit()->dict:
    profiles=[]
    for b1 in range(1,5):
        for b2 in range(1,min(b1,2)+1):
            profiles.append((b1,b2,1,1,1,1))
    profiles=tuple(sorted(set(profiles)))
    assert profiles==EXCLUDED_SORTED_PROFILES
    primes=(3,5,7,11,13,17)
    for profile in profiles:
        result=downset_proof_branch(primes,profile)
        assert result["noncovering_by_divisibility"] is True
    return {"excluded_sorted_profiles":profiles,"profile_count":len(profiles),"all_profiles_noncovering":True}
