"""M41: exact minimal exponent frontier after M40 closes P322.

The currently closed six-prime exponent down-set is generated by the M22 broad
regions together with the profile majorants closed in M33, M37, and M40:

    (4,4,1,1,1,1),
    (5,2,1,1,1,1),
    (3,2,2,1,1,1).

The componentwise-minimal sorted profiles outside that region are exactly

    (6,2,1,1,1,1),
    (5,3,1,1,1,1),
    (4,2,2,1,1,1),
    (3,3,2,1,1,1),
    (3,2,2,2,1,1).
"""
from __future__ import annotations

from m26_minimal_frontier import P322, sorted_profile
from m38_p52_profile_closure import P53, P62, profile_closed_after_m37

P422 = (4, 2, 2, 1, 1, 1)
P332 = (3, 3, 2, 1, 1, 1)
P3222 = (3, 2, 2, 2, 1, 1)
MINIMAL_FRONTIER = (P62, P53, P422, P332, P3222)


def profile_closed_after_m40(profile) -> bool:
    p = sorted_profile(profile)
    if profile_closed_after_m37(p):
        return True
    return all(a <= b for a, b in zip(p, P322))


def minimal_frontier_dominator(profile):
    p = sorted_profile(profile)
    if profile_closed_after_m40(p):
        return None

    assert p[1] >= 2
    if p[2] == 1:
        if p[1] >= 3:
            assert p[0] >= 5
            out = P53
        else:
            assert p[1] == 2 and p[0] >= 6
            out = P62
    else:
        assert p[2] >= 2 and p[0] >= 3
        if p[3] >= 2:
            out = P3222
        elif p[1] >= 3:
            out = P332
        else:
            assert p[1] == 2 and p[2] == 2 and p[0] >= 4
            out = P422

    assert all(a <= b for a, b in zip(out, p))
    return out


def frontier_audit() -> dict:
    assert all(not profile_closed_after_m40(p) for p in MINIMAL_FRONTIER)
    for p in MINIMAL_FRONTIER:
        for q in MINIMAL_FRONTIER:
            if p != q:
                assert not all(a <= b for a, b in zip(p, q))

    for p in MINIMAL_FRONTIER:
        assert minimal_frontier_dominator(p) == p

    assert profile_closed_after_m40(P322)
    assert minimal_frontier_dominator((9, 2, 1, 1, 1, 1)) == P62
    assert minimal_frontier_dominator((7, 4, 1, 1, 1, 1)) == P53
    assert minimal_frontier_dominator((8, 2, 2, 1, 1, 1)) == P422
    assert minimal_frontier_dominator((6, 4, 2, 1, 1, 1)) == P332
    assert minimal_frontier_dominator((5, 3, 2, 2, 1, 1)) == P3222
    return {"minimal_frontier": MINIMAL_FRONTIER, "verified": True}


__all__ = [
    "MINIMAL_FRONTIER", "P3222", "P332", "P422", "frontier_audit",
    "minimal_frontier_dominator", "profile_closed_after_m40",
]
