"""Optional fast exhaustive verifier for M58.

Requires numpy and numba.  Exact Fraction arithmetic is used only to generate
lookup-table entries; each lookup is rounded downward after multiplication by
Q.  The 67,108,864-state loop itself uses signed int64 only.  Thus the returned
minimum is a rigorous lower bound, not a floating-point search result.
"""
from __future__ import annotations

from fractions import Fraction

from m25_cross_support_seed import DIAGONAL, LAMBDA
from m58_p332_hard_seed import (
    C,
    COEFFICIENT_DEN,
    COEFFICIENT_NUMERATORS,
    D,
    DENOMINATORS,
    EXPECTED_ARGMIN,
    EXPECTED_FLOOR_MIN,
    EXPECTED_FLOOR_SLACK,
    EXPECTED_STATE_COUNT,
    Q,
    X5,
)

# Exact endpoint-derived ranges of the non-special rho numerators.  They can be
# independently regenerated by enumerating the 2^15 factor-4 endpoint box.
LOWS = (1,17,7,87,9,121,59,459,13,189,87,807,113,1185,699,2635)
HIGHS = (1,41,10,402,12,484,119,4695,16,648,159,6303,191,7599,1881,73057)


def _phi_exact(Cmask: int, numerator: int) -> Fraction:
    T = 15 ^ Cmask
    sm = 1 | (T << 1)
    cT = 8 if T & 1 else 1
    lo = X5 * Fraction(cT, DENOMINATORS[T])
    hi = 4 * lo
    rho = Fraction(numerator, DENOMINATORS[Cmask])
    nu = DIAGONAL[sm]
    linear = LAMBDA.get(sm, Fraction(0)) - rho
    x = -linear / (2 * nu)
    if x < lo:
        x = lo
    elif x > hi:
        x = hi
    return nu * x * x + linear * x


def _floor_tables():
    import numpy as np

    maxlen = max(hi - lo + 1 for lo, hi in zip(LOWS, HIGHS))
    phi = np.zeros((16, maxlen), dtype=np.int64)
    rho = np.zeros((16, maxlen), dtype=np.int64)
    for Cmask in range(16):
        for numerator in range(LOWS[Cmask], HIGHS[Cmask] + 1):
            idx = numerator - LOWS[Cmask]
            value = _phi_exact(Cmask, numerator)
            phi[Cmask, idx] = (value.numerator * Q) // value.denominator
            value = Fraction(numerator, DENOMINATORS[Cmask])
            rho[Cmask, idx] = (value.numerator * Q) // value.denominator
    return phi, rho


def verify_exhaustive() -> dict:
    """Run the rigorous 67,108,864-state integer lower-bound verification."""
    import numpy as np
    from numba import njit, prange

    phi_table, rho_table = _floor_tables()
    lows = np.array(LOWS, dtype=np.int64)
    Darr = np.array(D, dtype=np.int64)
    coeff = np.array(COEFFICIENT_NUMERATORS, dtype=np.int64)
    endpoints = np.empty((256, 8), dtype=np.int64)
    for bits in range(256):
        for j in range(8):
            endpoints[bits, j] = 4 if bits & (1 << j) else 1

    @njit
    def rho_nums(A1, B1, A3, B3, simple, eps):
        t = np.zeros(16, np.int64)
        t[1] = 8 + 7 * A1 + B1
        t[3] = 8 + 7 * A3 + B3
        smasks = (2, 4, 8, 6, 10)
        for i in range(5):
            t[smasks[i]] = simple[i]
        umasks = (5, 7, 9, 11, 12, 13, 14, 15)
        for i in range(8):
            m = umasks[i]
            t[m] = (8 if m & 1 else 1) * eps[i]

        n = np.zeros(16, np.int64)
        n[0] = 1
        for size in range(1, 5):
            for Cmask in range(1, 16):
                cc = Cmask
                pc = 0
                while cc:
                    pc += cc & 1
                    cc >>= 1
                if pc != size:
                    continue
                pivot = Cmask & -Cmask
                i = 0
                tmp = pivot
                while tmp > 1:
                    tmp >>= 1
                    i += 1
                rest = Cmask ^ pivot
                value = Darr[i] * n[rest]
                T = rest
                while True:
                    S = pivot | T
                    value -= t[S] * n[Cmask ^ S]
                    if T == 0:
                        break
                    T = (T - 1) & rest
                n[Cmask] = value
        return n

    @njit
    def evaluate(A1, B1, A3, B3, simple, eps):
        n = rho_nums(A1, B1, A3, B3, simple, eps)
        value = rho_table[15, n[15] - lows[15]]
        for Cmask in range(16):
            value += phi_table[Cmask, n[Cmask] - lows[Cmask]]

        units = 0
        units += coeff[0] * A1 + coeff[1] * B1
        units += coeff[2] * (A1 * (A1 - 1) // 2) + coeff[3] * (B1 * (B1 - 1) // 2)
        units += coeff[4] * A3 + coeff[5] * B3
        units += coeff[6] * (A3 * (A3 - 1) // 2) + coeff[7] * (B3 * (B3 - 1) // 2)
        k = 8
        for i in range(5):
            A = simple[i] - 1
            units += coeff[k] * A + coeff[k + 1] * (A * (A - 1) // 2)
            k += 2
        value += (Q // COEFFICIENT_DEN) * units
        return value

    @njit(parallel=True)
    def oracle():
        # 4^9 choices for four weighted activations and five simple levels;
        # each outer state scans all 2^8 unpenalized endpoint choices.
        nouter = 262_144
        values = np.empty(nouter, np.int64)
        best_eps = np.empty(nouter, np.int64)
        for ii in prange(nouter):
            A1 = (ii // 65536) % 4
            B1 = (ii // 16384) % 4
            A3 = (ii // 4096) % 4
            B3 = (ii // 1024) % 4
            simple = np.array((
                ((ii // 256) % 4) + 1,
                ((ii // 64) % 4) + 1,
                ((ii // 16) % 4) + 1,
                ((ii // 4) % 4) + 1,
                (ii % 4) + 1,
            ), dtype=np.int64)
            best = np.int64(9_000_000_000_000_000_000)
            bei = 0
            for ei in range(256):
                v = evaluate(A1, B1, A3, B3, simple, endpoints[ei])
                if v < best:
                    best = v
                    bei = ei
            values[ii] = best
            best_eps[ii] = bei

        bi = 0
        best = values[0]
        for ii in range(1, nouter):
            if values[ii] < best:
                best = values[ii]
                bi = ii
        state = (
            (bi // 65536) % 4,
            (bi // 16384) % 4,
            (bi // 4096) % 4,
            (bi // 1024) % 4,
            ((bi // 256) % 4) + 1,
            ((bi // 64) % 4) + 1,
            ((bi // 16) % 4) + 1,
            ((bi // 4) % 4) + 1,
            (bi % 4) + 1,
            best_eps[bi],
        )
        return best, state

    best, state = oracle()
    state = tuple(int(x) for x in state)
    assert EXPECTED_STATE_COUNT == 67_108_864
    assert int(best) == EXPECTED_FLOOR_MIN
    assert state == EXPECTED_ARGMIN
    assert int(C * Q) == 318_200_000_000
    assert int(best) - int(C * Q) == EXPECTED_FLOOR_SLACK > 0
    return {
        "state_count": EXPECTED_STATE_COUNT,
        "floor_min_scaled": int(best),
        "floor_slack_scaled": int(best) - int(C * Q),
        "argmin": state,
        "verified": True,
    }


if __name__ == "__main__":
    print(verify_exhaustive())


__all__ = ["verify_exhaustive"]
